# -*- coding: utf-8 -*-
"""Homework_1_.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19fjH29E89dL2X8Q0QIOmM_E5hss2C5Hk
"""

#   Homework_1

t=[[1],[2],[3],[4],[5],[6],[7],[8],[9]]

for i in range(9):
    s = int(input("Bir sayı giriniz: "))
    if s >= 1 and s <= 100:s
      t[i] = s
    else:
      print("Lütfen 1 ile 100 arasında bir sayı giriniz")

print(t[:3])
print(t[3:6])
print(t[6:9])